name:                superrecords-playground
version:             0.1.0.0
github:              "pranaysashank/superrecords-playground"
license:             BSD3
author:              "Pranay Sashank"
maintainer:          "pranaysashank@gmail.com"
copyright:           "2018 Pranay Sashank"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pranaysashank/superrecords#readme>

dependencies:
- base >= 4.7 && < 5
- product-profunctors
- profunctors
- superrecord

library:
  source-dirs: src

executables:
  superrecords-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - superrecords-playground

tests:
  superrecords-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - superrecords-playground
